### ISSUE TITLE
what to copy for riverview

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Holyoke-History-Room#1]
@sedelson31 can you please alert Nick to what should be copied (and where) from your private repo to https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/tree/main/Riverview_Renewal_Project?

I will be announcing this public repo at the presentations tomorrow and would like it to include the spreadsheet and the scans

Thanks in advance, Nick

**Comment by sedelson31** [comment]
Just the `riverview_organized` folder (I don't think the original scans are necessary) and the `riverview_renewal_data_2023_05_08.xlsx` spreadsheet. 

These are both currently within the `riverview` folder

**Comment by sedelson31** [comment]
Note that I just updated the spreadsheet and renamed it accordingly.

**Comment by nicholasjhorton** [comment]
Adding spreadsheet. More to follow soon. See https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/commit/28d81cb5c019e85b763c45efe48edc2ebba76c47

**Comment by nicholasjhorton** [comment]
@LorraineOloo and @sedelson31 is there anything else that you'd like to make accessible in the public repo? In particular, should I add your final report? Thanks in advance for any guidance.

**Comment by sedelson31** [comment]
adding the final report would be great - thanks!

**Comment by nicholasjhorton** [comment]
Thanks! Done via https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/commit/3d3b7bad0342b99401183f9cefde0e6c964bc913
