### ISSUE TITLE
add information regarding existing finding aid (box number or similar?) for Riverview README.md

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Holyoke-History-Room#2]
@sedelson31 can you please flesh out the stub description at https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/tree/main/Riverview_Renewal_Project/README.md

Much of this should be possible to copy from the private repo.

Once you add your commit URL @LorraineOloo and I can review this and #1

**Comment by sedelson31** [comment]
Just pushed.

**Comment by nicholasjhorton** [comment]
This looks great: see https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/commit/8be9cc7212879b5fde5001cdb1b42dd685d186f9

**Comment by nicholasjhorton** [comment]
@sedelson31 can you please add a link to the finding aid (or similar) to this README.md as well as for your report?

**Comment by nicholasjhorton** [comment]
The addition of the mention of the finding aid would be very helpful for Eileen.

**Comment by sedelson31** [comment]
I looked at the [collections](http://www.holyokelibrary.org/historycollection.asp) page of the Holyoke History Room and there is nothing that mentions Riverview.
