### ISSUE TITLE
flesh out README.md file for Municipal Reports

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Holyoke-History-Room#3]
@NahiaP can you please flesh out the https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/blob/main/Municipal_Reports/README.md for the municipal reports project? This will be needed for the presentations on Tuesday.

I'll open a separate issue for the addition of the scans and transcriptions.

**Comment by nicholasjhorton** [comment]
@NahiaP any updates on this front?

**Comment by NahiaP** [comment]
I just added the txt files that I created and ran through the cleaning function and updated the readme. I also added some links. Should I also upload material related to the analysis?

**Comment by nicholasjhorton** [comment]
Looks good, thanks!
