### ISSUE TITLE
flesh out README for the Parsons employee listing

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Holyoke-History-Room#6]
https://github.com/STAT210-S23/STAT210-Holyoke-History-Room/blob/main/Parsons_Paper_Company_payroll_register/README.md

This will be needed for the presentations on Tuesday.

**Comment by nicholasjhorton** [comment]
@Cheafitz25 any updates on this front? Thanks in advance for any guidance.

**Comment by Cheafitz25** [comment]
Yes apologies, I sent message on Slack, its all good.
