### ISSUE TITLE
copy scanned pdf and preliminary draft of the csv file with parsed addresses 

### ISSUE THREAD

**Issue by nicholasjhorton** [STAT210-S23/STAT210-Holyoke-History-Room#7]
@kjinsanity can you please copy the scanned pdf and the preliminary/working draft of the csv file with the parsed addresses to this repo (then close this issue)?

See also #4

**Comment by kjinsanity** [comment]
The scanned pdf has too large of a file size, should I just include a link to the online version?

**Comment by nicholasjhorton** [comment]
Yes.
